### ISSUE TITLE
need atomic operations on depth_d array ? 

### ISSUE THREAD

**Issue by guowentian** [iHeartGraph/Enterprise#1]
If the application is shortest path instead of a simple breadth-first search, I suspect there is a need for atomic operations on depth_d, for example, at expander.cuh line 163. 
Because there might be 2 threads simultaneously execute line 162, and try to update depth_d at the same time at line 163 since both of them think aq_ver_curr is unvisited. It is fine in BFS because in each iteration LEVEL is the same. However, in shortest path, the update is like depth_d[aq_ver_curr] = min(depth_d[aq_ver_curr], new_value), then one need a lock on depth_d[aq_ver_curr] ??

**Comment by iHeartGraph** [comment]
That's right! We are actively working on SSSP, PageRank right now. Will post another high-performance project that includes all these graph algorithms soon!
