### ISSUE TITLE
sml_scan,mid_scan,lrg_scan are not called

### ISSUE THREAD

**Issue by foxspy** [iHeartGraph/Enterprise#3]
It seems that the sml_scan,mid_scan,lrg_scan(in scan.cuh) are not called by any other function.Though these kernel functions have been implemented,I could not find any code to launch these kernel.I have seen Enterprise use these method to achieve load balance.How could this version achieve the goal?

**Comment by iHeartGraph** [comment]
Thanks for your question. Please check the corresponding answers in the following paragraphs.

**- It seems that the sml_scan,mid_scan,lrg_scan(in scan.cuh) are not called by any other function. Though these kernel functions have been implemented,I could not find any code to launch these kernel.**
+ Yes. These functions are not used by any functions in Enterprise source code.


**-I have seen Enterprise use these method to achieve load balance.How could this version achieve the goal?**
+ First, these functions are just used for computing prefix scans, which are explained [here](https://en.wikipedia.org/wiki/Prefix_sum) and the source can be found [here](http://http.developer.nvidia.com/GPUGems3/gpugems3_ch39.html). Therefore, **they have nothing to do with workload balancing**.
+ Second, for workload balancing. They are achieved through two steps. First step, generating multiple frontier queues while scanning status array. Specific code are in this [range](https://github.com/iHeartGraph/Enterprise/blob/master/inspector.cuh#L438-L733). Second step, assigning various granularity of threads to work on those multiple frontier queues. Specific source code are [here](https://github.com/iHeartGraph/Enterprise/blob/master/expander.cuh#L837-L920).

**Comment by foxspy** [comment]
Get it! Thanks for your kind response.
