### ISSUE TITLE
Doubts about traversing on directed graph

### ISSUE THREAD

**Issue by foxspy** [iHeartGraph/Enterprise#4]
It is confusing that the expand operation during top-down ([eg. thread traverse](https://github.com/iHeartGraph/Enterprise/blob/master/expander.cuh#L132-L167)) bottom-up ([eg. thread traverse](https://github.com/iHeartGraph/Enterprise/blob/master/expander.cuh#L485-L526)) stage use the same data structure adj_list_d (csr structure).Through the tuple_text_to_bin.cpp, it is clear that the adj_list_d store the out-neighbor-list, but during the bottom-up the expand operation should check the in-neighbors-list not the out-neighbors-list, and I have not find the switch function from csr to in-neighbor-list(csc) and the csr looks like a read only structure because it was stored in texture memory, and only when we compute on a symmetric graph that the in-neighbor-list is equal to the out-neighbor-list.

**Comment by asherliu** [comment]
@foxspy Right. This version of Enterprise source code only works for undirected graphs.

**Comment by foxspy** [comment]
Thanks!
