### ISSUE TITLE
test initialization issue

### ISSUE THREAD

**Issue by nil77** [iHeartGraph/Enterprise#5]
the code init the 64 tests apparently has issue.

/*Generate non-redundant non-orphan source list*/
	vertex_t *src_list=new vertex_t[64];
	for(long i=0;i<64;i++)
	{	
		if(ginst->beg_pos[src+1]-ginst->beg_pos[src] !=0)
		{
		  // src_list[i] got value	
		}
               //*****src_list[i] were left un-inited ...err
	}

**Comment by iHeartGraph** [comment]
Good point. Just solved the problem.

**Comment by nil77** [comment]
another approach is to remove i++ from for loop and only advance when src_list got eligible value. And it brings another problem if there is not enough qualified values (<64). :)
